### ISSUE TITLE
Figure out how to collect metrics

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/google-cloud-graalvm-support#12]
Figure out how to collect metrics.

**Comment by dzou** [comment]
Notes from Elena:

Look into

ServiceOptions.setClientLibToken
and ServiceOptions.setHeaderProvider

As possible hooks to add user agent strings.

**Comment by dzou** [comment]
I learned that the JVM Code in the `ApiClientHeaderProvider` can't be used.

One must check the setting: `System.getProperty("org.graalvm.nativeimage.imagecode") == "runtime"` to determine if the code is running as GraalVM image at runtime.

I think the best way is to come up with a very simple substitution which checks this property and modifies one of the headers.

Ideally, we modify code in https://github.com/googleapis/gax-java/blob/master/gax/src/main/java/com/google/api/gax/core/GaxProperties.java#L83

Override Java Version maybe?

**Comment by meltsufin** [comment]
Sure, we can try the version. Is that field going to be easily accessible for us in the reports?

**Comment by dzou** [comment]
Completed in https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support/pull/50
