### ISSUE TITLE
Investigate the usage of GoogleApiGaxGrpcSubstitutions from the Quarkus Extension repo

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/google-cloud-graalvm-support#65]
Following up on the conversation to https://github.com/quarkiverse/quarkiverse-google-cloud-services/pull/72

In the Quarkiverse Extension for GCP, there a [Gax substitution](https://github.com/quarkiverse/quarkiverse-google-cloud-services/blob/6b7be8c11cc5f635ae0a757bee66a9bf755fecd1/common/grpc/src/main/java/io/quarkiverse/googlecloudservices/common/grpc/runtime/graal/GoogleApiGaxGrpcSubstitutions.java#L62) that is used. We can add this substitution to our repo or more ideally be able to contribute this back to upstream libraries.

According to the above context in https://github.com/quarkiverse/quarkiverse-google-cloud-services/pull/72#issuecomment-758030271, 

> This substitution support using GRPC in a native image not deployed on Google Cloud.
> It provides a substitution for `com.google.api.gax.grpc.InstantiatingGrpcChannelProvider` without some part of the code that need a `ComputeEngineCredentials` class that is not present if not running on Google Cloud.
> 
> See
> 
> https://github.com/quarkiverse/quarkiverse-google-cloud-services/blob/6b7be8c11cc5f635ae0a757bee66a9bf755fecd1/common/grpc/src/main/java/io/quarkiverse/googlecloudservices/common/grpc/runtime/graal/GoogleApiGaxGrpcSubstitutions.java#L62
> 
> I can send a PR upstream with this substitution or the code can be changed upstream to didn't rely on the presence of the `ComputeEngineCredentials` class.

Seems like the code should be rewritten to check classpath for `ComputeEngineCredentials` before referencing this class?

@loicmathieu -- So far we actually haven't needed this substitution in our samples it seems. Maybe we can first figure out how to reproduce the issue locally. There is a minor difference in our sample code in which we rely on `grpc-netty-shaded`, whereas the Quarkus samples rely on Quarkus's version of netty.

**Comment by loicmathieu** [comment]
I will provide a small reproducer for this.

**Comment by dzou** [comment]
> I will provide a small reproducer for this.

Thanks Loic, this would be a great help.

**Comment by dzou** [comment]
Will close this for now because it seems like it may no longer be an issue. Let me know if something arises, though.
