### ISSUE TITLE
feature request: Google Cloud Datastore support

### ISSUE THREAD

**Issue by kenyee** [GoogleCloudPlatform/google-cloud-graalvm-support#66]
This issue suggested asking for this here: https://github.com/googleapis/java-datastore/issues/20

Wondering if Google Cloud Datastore support is planned for graalvm as well?  
It's a nice layer over BigTable :-)

**Comment by dzou** [comment]
@kenyee - Hey thanks for the feature request. Yes we would be very happy to add datastore support and a corresponding sample app.

We're an early project, so we're interested in learning where else to contribute to the GraalVM ecosystem for Google Cloud developers (i.e. whether it be frameworks like Quarkus, Micronaut, Spring or elsewhere). If you have any more ideas, please feel free to let us know; it helps us a lot to be pointed in the right direction!

**Comment by kenyee** [comment]
Thanks David.  Quarkus is what I was planning on using it on.
The Spring Data integration is so much nicer though...saw a Ray Tsang video on it and it was crazy easy to use :-)

**Comment by dzou** [comment]
Gotcha, thanks for the feedback. We're interested in researching ways to make using Quarkus with GCP easier.

I just did some testing with Datastore, and it looks like version `0.2.0` of our library should be compatible with datastore client libraries.

So you should be able to compile your Quarkus app using datastore using these deps:

```
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-graalvm-support</artifactId>
      <version>0.2.0</version>
    </dependency>

    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-datastore</artifactId>
    </dependency>
```
