### ISSUE TITLE
Add Cloud Tasks Sample

### ISSUE THREAD

**Issue by kostacasa** [GoogleCloudPlatform/google-cloud-graalvm-support#76]
I just wanted to say we chanced it and added the Cloud Tasks module to our Quarkus project with this library and it seems to work well - we tested task creation with both OIDC and OAuth authorization schemes. I can create a small PR that adds an example and a test perhaps?

**Comment by dzou** [comment]
That's great. Yeah sure, we would be very happy to accept a contribution!

**Comment by dzou** [comment]
Fixed by: https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support/pull/78
